# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20150808_1621'),
        ('clubs', '0001_initial'),
        ('nations', '0002_auto_20150804_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ea_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_small', models.CharField(max_length=500)),
                ('image_medium', models.CharField(max_length=500)),
                ('image_large', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=3, choices=[('gk', 'GK'), ('rwb', 'RWB'), ('rb', 'RB'), ('cb', 'CB'), ('lb', 'LB'), ('lwb', 'LWB'), ('cdm', 'CDM'), ('cm', 'CM'), ('cam', 'CAM'), ('rm', 'RM'), ('rw', 'RW'), ('rf', 'RF'), ('lm', 'LM'), ('lw', 'LW'), ('lf', 'LF'), ('cf', 'CF'), ('st', 'ST')])),
                ('position_line', models.CharField(max_length=3, choices=[('gk', 'GK'), ('def', 'DEF'), ('mid', 'MID'), ('att', 'ATT')])),
                ('position_full', models.CharField(max_length=3)),
                ('birthdate', models.DateField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('acceleration', models.PositiveIntegerField()),
                ('aggression', models.PositiveIntegerField()),
                ('agility', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('ball_control', models.PositiveIntegerField()),
                ('foot', models.PositiveIntegerField()),
                ('skill', models.PositiveIntegerField()),
                ('crossing', models.PositiveIntegerField()),
                ('curve', models.PositiveIntegerField()),
                ('dribbling', models.PositiveIntegerField()),
                ('finishing', models.PositiveIntegerField()),
                ('free_kick_accuracy', models.PositiveIntegerField()),
                ('gk_diving', models.PositiveIntegerField()),
                ('gk_handling', models.PositiveIntegerField()),
                ('gk_kicking', models.PositiveIntegerField()),
                ('gk_positioning', models.PositiveIntegerField()),
                ('gk_reflex', models.PositiveIntegerField()),
                ('heading_accuracy', models.PositiveIntegerField()),
                ('interceptions', models.PositiveIntegerField()),
                ('jumping', models.PositiveIntegerField()),
                ('long_passing', models.PositiveIntegerField()),
                ('long_shots', models.PositiveIntegerField()),
                ('marking', models.PositiveIntegerField()),
                ('penalties', models.PositiveIntegerField()),
                ('positioning', models.PositiveIntegerField()),
                ('potential', models.PositiveIntegerField()),
                ('reactions', models.PositiveIntegerField()),
                ('short_passing', models.PositiveIntegerField()),
                ('shot_power', models.PositiveIntegerField()),
                ('sliding_tackle', models.PositiveIntegerField()),
                ('sprint_speed', models.PositiveIntegerField()),
                ('standing_tackle', models.PositiveIntegerField()),
                ('stamina', models.PositiveIntegerField()),
                ('strength', models.PositiveIntegerField()),
                ('vision', models.PositiveIntegerField()),
                ('volleys', models.PositiveIntegerField()),
                ('weak_foot', models.PositiveIntegerField()),
                ('traits', models.CharField(max_length=500, null=True)),
                ('specialities', models.CharField(max_length=500, null=True)),
                ('workrate_att', models.CharField(max_length=10, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')])),
                ('workrate_def', models.CharField(max_length=10, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')])),
                ('card_att_1', models.PositiveIntegerField()),
                ('card_att_2', models.PositiveIntegerField()),
                ('card_att_3', models.PositiveIntegerField()),
                ('card_att_4', models.PositiveIntegerField()),
                ('card_att_5', models.PositiveIntegerField()),
                ('card_att_6', models.PositiveIntegerField()),
                ('overall_rating', models.PositiveIntegerField()),
                ('ea_id_unique', models.CharField(max_length=255)),
                ('play_style', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('player_type', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('is_goalkeeper', models.BooleanField(default=False)),
                ('is_special_type', models.BooleanField(default=False)),
                ('club', models.ForeignKey(to='clubs.Club')),
                ('league', models.ForeignKey(to='leagues.League')),
                ('nation', models.ForeignKey(to='nations.Nation')),
            ],
            options={
                'verbose_name_plural': 'Players',
                'verbose_name': 'Player',
                'ordering': ('order', 'overall_rating', 'common_name', 'pk'),
            },
        ),
    ]
