# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20150817_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aggression',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='agility',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ball_control',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='crossing',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='curve',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='finishing',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_kick_accuracy',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_diving',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_handling',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_kicking',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_positioning',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_reflex',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='heading_accuracy',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='interceptions',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumping',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_passing',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_shots',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='marking',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='overall_rating',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='positioning',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='reactions',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_passing',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='shot_power',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sliding_tackle',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sprint_speed',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='standing_tackle',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='volleys',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weak_foot',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
